readability:
  flesch_reading_ease: {target: 80, min: 75, max: 88}
lexicon:
  common_words_pct: {target: 81, min: 78, max: 85}
  complex_words_pct: {target: 7, min: 5, max: 9}
  unique_words_pct: {target: 48, min: 45, max: 52}
  avg_word_len: {target: 4.1, min: 3.9, max: 4.3}
verbs:
  active_pct: {target: 98, min: 95, max: 99}
  auxiliary_pct: {target: 12, min: 8, max: 17}
  continuous_pct: {target: 12, min: 8, max: 15}
sentences:
  avg_len: {target: 13, min: 9.7, max: 15.6}
dialogue:
  proportion_pct: {target: 42, min: 9, max: 76}
pace:
  score: {target: 47, min: 40, max: 57}
affect:
  overall_tone: {target: -0.3, min: -0.4, max: -0.1}
  anger_pct: {target: 38, min: 33, max: 45}
  fear_pct: {target: 40, min: 34, max: 47}
  happiness_pct: {target: 41, min: 34, max: 47}
  disgust_pct: {target: 16, min: 13, max: 20}
  surprise_pct: {target: 40, min: 34, max: 46}
  sadness_pct: {target: 31, min: 27, max: 36}
  neutral_pct: {target: 16, min: 14, max: 18}
pos:
  nouns_pct: {target: 19, min: 17, max: 23}
  verbs_pct: {target: 21, min: 19, max: 24}
  adjectives_pct: {target: 6, min: 4, max: 7}
  adverbs_pct: {target: 8, min: 6, max: 10}
  pronouns_pct: {target: 15, min: 11, max: 18}
  other_pct: {target: 30, min: 27, max: 33}