# Node 20-alpine base image
FROM node:20-alpine

# Set working directory
WORKDIR /app/ui

# Copy package files for caching
COPY frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the UI code
COPY frontend/ .

# Expose port
EXPOSE 3000

# Development command
CMD ["npm", "run", "dev", "--", "-p", "3000"]