# Agent configuration for Writers Room X as specified in Prompt 26

supervisor: 
  model: "reasoner-1"
  max_tokens: 4000
  temperature: 0.2

lore_archivist: 
  model: "reasoner-1"
  temperature: 0.3
  tools: ["rag", "citations"]

grim_editor: 
  model: "stylist-1"
  temperature: 0.7
  tools: ["diff", "metrics"]

dialogue_demon: 
  model: "stylist-1"
  temperature: 0.8
  tools: ["diff"]

pacing_surgeon: 
  model: "reasoner-1"
  temperature: 0.5
  tools: ["metrics", "diff"]

plot_twister: 
  model: "reasoner-1"
  temperature: 0.6

tone_metrics: 
  model: "critic-1"
  temperature: 0.2
  tools: ["metrics"]

red_team: 
  model: "stylist-1"
  temperature: 0.9
  tools: ["diff"]

reviewer_pack: 
  model: "reasoner-1"
  temperature: 0.5

voice_simulator: 
  model: "stylist-1"
  temperature: 0.8