# Metrics configuration for Writers Room X
# Based on Editorial Distance (ED) methodology

targets:
  readability:
    flesch_reading_ease:
      min: 70
      max: 80
      weight: 0.2
    flesch_kincaid_grade:
      min: 6
      max: 8
      weight: 0.15

  sentence_structure:
    avg_sentence_length:
      min: 12
      max: 18
      weight: 0.15
    max_sentence_length:
      max: 35
      weight: 0.1

  word_usage:
    avg_syllables_per_word:
      min: 1.3
      max: 1.6
      weight: 0.1
    unique_word_ratio:
      min: 0.4
      max: 0.6
      weight: 0.1

  parts_of_speech:
    active_verb_ratio:
      min: 0.15
      max: 0.25
      weight: 0.1
    noun_to_verb_ratio:
      min: 1.5
      max: 2.5
      weight: 0.05
    adjective_ratio:
      max: 0.08
      weight: 0.05

  dialogue:
    dialogue_percentage:
      min: 0.3
      max: 0.5
      weight: 0.1
    
thresholds:
  green: 0.85  # Score >= 85% of target
  yellow: 0.70  # Score >= 70% of target
  red: 0.00     # Score < 70% of target

analysis_levels:
  basic:
    - flesch_reading_ease
    - avg_sentence_length
    - active_verb_ratio
  
  standard:
    - flesch_reading_ease
    - flesch_kincaid_grade
    - avg_sentence_length
    - active_verb_ratio
    - dialogue_percentage
  
  comprehensive:
    - all

reporting:
  include_suggestions: true
  show_comparisons: true
  highlight_outliers: true
  max_suggestions: 5